/* 수강신청 */
DROP TABLE LEC_REQS 
	CASCADE CONSTRAINTS;

/* 학생 */
DROP TABLE STUDENTS 
	CASCADE CONSTRAINTS;

/* 강의 */
DROP TABLE LECTS 
	CASCADE CONSTRAINTS;

/* 교육장 */
DROP TABLE CLS_ROOMS 
	CASCADE CONSTRAINTS;

/* 매니저 */
DROP TABLE MGRS 
	CASCADE CONSTRAINTS;

/* 강사 */
DROP TABLE TEACHS 
	CASCADE CONSTRAINTS;

/* 강의배정 */
DROP TABLE LECT_TEACH 
	CASCADE CONSTRAINTS;

/* 주소 */
DROP TABLE ADDRS 
	CASCADE CONSTRAINTS;

/* 강의실사진 */
DROP TABLE CR_PHTOS 
	CASCADE CONSTRAINTS;

/* 강사사진 */
DROP TABLE TEA_PHTOS 
	CASCADE CONSTRAINTS;

/* 수강신청 */
CREATE TABLE LEC_REQS (
	LRNO INTEGER NOT NULL, /* 수강신청일련번호 */
	LNO INTEGER NOT NULL, /* 강의일련번호 */
	SNO INTEGER NOT NULL, /* 학생일련번호 */
	CDATE DATE NOT NULL, /* 수강신청일 */
	PAY_TYPE INTEGER, /* 수강료 결제유형 */
	PAY_YN CHAR(1), /* 수강료 결제여부 */
	PAY_DT DATE /* 수강료 결제일 */
);

COMMENT ON TABLE LEC_REQS IS '수강신청';

COMMENT ON COLUMN LEC_REQS.LRNO IS '수강신청일련번호';

COMMENT ON COLUMN LEC_REQS.LNO IS '강의일련번호';

COMMENT ON COLUMN LEC_REQS.SNO IS '학생일련번호';

COMMENT ON COLUMN LEC_REQS.CDATE IS '수강신청일';

COMMENT ON COLUMN LEC_REQS.PAY_TYPE IS '수강료 결제유형';

COMMENT ON COLUMN LEC_REQS.PAY_YN IS '수강료 결제여부';

COMMENT ON COLUMN LEC_REQS.PAY_DT IS '수강료 결제일';

CREATE UNIQUE INDEX PK_LEC_REQS
	ON LEC_REQS (
		LRNO ASC
	);

ALTER TABLE LEC_REQS
	ADD
		CONSTRAINT PK_LEC_REQS
		PRIMARY KEY (
			LRNO
		);

/* 학생 */
CREATE TABLE STUDENTS (
	SNO INTEGER NOT NULL, /* 학생일련번호 */
	SNAME VARCHAR2(50) NOT NULL, /* 학생명 */
	EMAIL VARCHAR2(40) NOT NULL, /* 학생이메일 */
	TEL VARCHAR2(30) NOT NULL, /* 학생전화 */
	ANO INTEGER, /* 주소일련번호 */
	DET_ADDR VARCHAR2(255), /* 상세주소 */
	SCHOOL INTEGER, /* 학생최종학력 */
	WORKING CHAR(1) NOT NULL /* 학생직장인여부 */
);

COMMENT ON TABLE STUDENTS IS '학생';

COMMENT ON COLUMN STUDENTS.SNO IS '학생일련번호';

COMMENT ON COLUMN STUDENTS.SNAME IS '학생명';

COMMENT ON COLUMN STUDENTS.EMAIL IS '학생이메일';

COMMENT ON COLUMN STUDENTS.TEL IS '학생전화';

COMMENT ON COLUMN STUDENTS.ANO IS '주소일련번호';

COMMENT ON COLUMN STUDENTS.DET_ADDR IS '상세주소';

COMMENT ON COLUMN STUDENTS.SCHOOL IS '학생최종학력';

COMMENT ON COLUMN STUDENTS.WORKING IS '학생직장인여부';

CREATE UNIQUE INDEX PK_STUDENTS
	ON STUDENTS (
		SNO ASC
	);

CREATE UNIQUE INDEX UIX_STUDENTS
	ON STUDENTS (
		EMAIL ASC
	);

CREATE INDEX IX_STUDENTS
	ON STUDENTS (
		SNAME ASC
	);

ALTER TABLE STUDENTS
	ADD
		CONSTRAINT PK_STUDENTS
		PRIMARY KEY (
			SNO
		);

ALTER TABLE STUDENTS
	ADD
		CONSTRAINT UK_STUDENTS
		UNIQUE (
			EMAIL
		);

/* 강의 */
CREATE TABLE LECTS (
	LNO INTEGER NOT NULL, /* 강의일련번호 */
	TITLE VARCHAR(255) NOT NULL, /* 강의명 */
	SDATE DATE NOT NULL, /* 강의시작일 */
	EDATE DATE NOT NULL, /* 강의종료일 */
	TOT_HR INTEGER NOT NULL, /* 총강의시간 */
	TOT_DAYS INTEGER NOT NULL, /* 강의일수 */
	CAPACITY INTEGER, /* 총수강인원 */
	REQ INTEGER, /* 수강신청자 */
	MNO INTEGER, /* 매니저일련번호 */
	CRNO INTEGER /* 교육장일련번호 */
);

COMMENT ON TABLE LECTS IS '강의';

COMMENT ON COLUMN LECTS.LNO IS '강의일련번호';

COMMENT ON COLUMN LECTS.TITLE IS '강의명';

COMMENT ON COLUMN LECTS.SDATE IS '강의시작일';

COMMENT ON COLUMN LECTS.EDATE IS '강의종료일';

COMMENT ON COLUMN LECTS.TOT_HR IS '총강의시간';

COMMENT ON COLUMN LECTS.TOT_DAYS IS '강의일수';

COMMENT ON COLUMN LECTS.CAPACITY IS '총수강인원';

COMMENT ON COLUMN LECTS.REQ IS '수강신청자';

COMMENT ON COLUMN LECTS.MNO IS '매니저일련번호';

COMMENT ON COLUMN LECTS.CRNO IS '교육장일련번호';

CREATE UNIQUE INDEX PK_LECTS
	ON LECTS (
		LNO ASC
	);

CREATE INDEX IX_LECTS
	ON LECTS (
		TITLE ASC
	);

ALTER TABLE LECTS
	ADD
		CONSTRAINT PK_LECTS
		PRIMARY KEY (
			LNO
		);

/* 교육장 */
CREATE TABLE CLS_ROOMS (
	CRNO INTEGER NOT NULL, /* 교육장일련번호 */
	LOC VARCHAR2(50) NOT NULL, /* 교육장 */
	CRNAME VARCHAR2(50) NOT NULL /* 강의실 */
);

COMMENT ON TABLE CLS_ROOMS IS '교육장';

COMMENT ON COLUMN CLS_ROOMS.CRNO IS '교육장일련번호';

COMMENT ON COLUMN CLS_ROOMS.LOC IS '교육장';

COMMENT ON COLUMN CLS_ROOMS.CRNAME IS '강의실';

CREATE UNIQUE INDEX PK_CLS_ROOMS
	ON CLS_ROOMS (
		CRNO ASC
	);

CREATE UNIQUE INDEX UIX_CLS_ROOMS
	ON CLS_ROOMS (
		LOC ASC,
		CRNAME ASC
	);

ALTER TABLE CLS_ROOMS
	ADD
		CONSTRAINT PK_CLS_ROOMS
		PRIMARY KEY (
			CRNO
		);

ALTER TABLE CLS_ROOMS
	ADD
		CONSTRAINT UK_CLS_ROOMS
		UNIQUE (
			LOC,
			CRNAME
		);

/* 매니저 */
CREATE TABLE MGRS (
	MNO INTEGER NOT NULL, /* 매니저일련번호 */
	MNAME VARCHAR2(50) NOT NULL, /* 매니저명 */
	TEL VARCHAR2(30) NOT NULL, /* 매니저전화 */
	EMAIL VARCHAR2(40) NOT NULL /* 매니저이메일 */
);

COMMENT ON TABLE MGRS IS '매니저';

COMMENT ON COLUMN MGRS.MNO IS '매니저일련번호';

COMMENT ON COLUMN MGRS.MNAME IS '매니저명';

COMMENT ON COLUMN MGRS.TEL IS '매니저전화';

COMMENT ON COLUMN MGRS.EMAIL IS '매니저이메일';

CREATE UNIQUE INDEX PK_MGRS
	ON MGRS (
		MNO ASC
	);

CREATE UNIQUE INDEX UIX_MGRS
	ON MGRS (
		EMAIL ASC
	);

ALTER TABLE MGRS
	ADD
		CONSTRAINT PK_MGRS
		PRIMARY KEY (
			MNO
		);

ALTER TABLE MGRS
	ADD
		CONSTRAINT UK_MGRS
		UNIQUE (
			EMAIL
		);

/* 강사 */
CREATE TABLE TEACHS (
	TNO INTEGER NOT NULL, /* 강사일련번호 */
	TNAME VARCHAR2(50) NOT NULL, /* 강사명 */
	TEL VARCHAR2(30) NOT NULL, /* 강사전화 */
	EMAIL VARCHAR2(40) NOT NULL, /* 강사이메일 */
	ANO INTEGER, /* 주소일련번호 */
	DET_ADDR VARCHAR2(255), /* 상세주소 */
	PAY INTEGER /* 강사료 */
);

COMMENT ON TABLE TEACHS IS '강사';

COMMENT ON COLUMN TEACHS.TNO IS '강사일련번호';

COMMENT ON COLUMN TEACHS.TNAME IS '강사명';

COMMENT ON COLUMN TEACHS.TEL IS '강사전화';

COMMENT ON COLUMN TEACHS.EMAIL IS '강사이메일';

COMMENT ON COLUMN TEACHS.ANO IS '주소일련번호';

COMMENT ON COLUMN TEACHS.DET_ADDR IS '상세주소';

COMMENT ON COLUMN TEACHS.PAY IS '강사료';

CREATE UNIQUE INDEX PK_TEACHS
	ON TEACHS (
		TNO ASC
	);

CREATE UNIQUE INDEX UIX_TEACHS
	ON TEACHS (
		EMAIL ASC
	);

ALTER TABLE TEACHS
	ADD
		CONSTRAINT PK_TEACHS
		PRIMARY KEY (
			TNO
		);

ALTER TABLE TEACHS
	ADD
		CONSTRAINT UK_TEACHS
		UNIQUE (
			EMAIL
		);

/* 강의배정 */
CREATE TABLE LECT_TEACH (
	LNO INTEGER NOT NULL, /* 강의일련번호 */
	TNO INTEGER NOT NULL, /* 강사일련번호 */
	TITLE <지정 되지 않음> NOT NULL, /* 과목명 */
	SDATE DATE, /* 강의시작일 */
	EDATE DATE /* 강의종료일 */
);

COMMENT ON TABLE LECT_TEACH IS '강의배정';

COMMENT ON COLUMN LECT_TEACH.LNO IS '강의일련번호';

COMMENT ON COLUMN LECT_TEACH.TNO IS '강사일련번호';

COMMENT ON COLUMN LECT_TEACH.TITLE IS '과목명';

COMMENT ON COLUMN LECT_TEACH.SDATE IS '강의시작일';

COMMENT ON COLUMN LECT_TEACH.EDATE IS '강의종료일';

CREATE UNIQUE INDEX PK_LECT_TEACH
	ON LECT_TEACH (
		LNO ASC,
		TNO ASC
	);

ALTER TABLE LECT_TEACH
	ADD
		CONSTRAINT PK_LECT_TEACH
		PRIMARY KEY (
			LNO,
			TNO
		);

/* 주소 */
CREATE TABLE ADDRS (
	ANO INTEGER NOT NULL, /* 주소일련번호 */
	POSTNO INTEGER NOT NULL, /* 우편번호 */
	BASE_ADDR VARCHAR2(255) NOT NULL /* 기본주소 */
);

COMMENT ON TABLE ADDRS IS '주소';

COMMENT ON COLUMN ADDRS.ANO IS '주소일련번호';

COMMENT ON COLUMN ADDRS.POSTNO IS '우편번호';

COMMENT ON COLUMN ADDRS.BASE_ADDR IS '기본주소';

CREATE UNIQUE INDEX PK_ADDRS
	ON ADDRS (
		ANO ASC
	);

ALTER TABLE ADDRS
	ADD
		CONSTRAINT PK_ADDRS
		PRIMARY KEY (
			ANO
		);

/* 강의실사진 */
CREATE TABLE CR_PHTOS (
	CRPNO INTEGER NOT NULL, /* 강의실사진일련번호 */
	PHTO_PATH VARCHAR2(255) NOT NULL, /* 사진경로 */
	CRNO INTEGER NOT NULL /* 교육장일련번호 */
);

COMMENT ON TABLE CR_PHTOS IS '강의실사진';

COMMENT ON COLUMN CR_PHTOS.CRPNO IS '강의실사진일련번호';

COMMENT ON COLUMN CR_PHTOS.PHTO_PATH IS '사진경로';

COMMENT ON COLUMN CR_PHTOS.CRNO IS '교육장일련번호';

CREATE UNIQUE INDEX PK_CR_PHTOS
	ON CR_PHTOS (
		CRPNO ASC
	);

ALTER TABLE CR_PHTOS
	ADD
		CONSTRAINT PK_CR_PHTOS
		PRIMARY KEY (
			CRPNO
		);

/* 강사사진 */
CREATE TABLE TEA_PHTOS (
	TNO INTEGER NOT NULL, /* 강사일련번호 */
	PHTO_PATH VARCHAR2(255) NOT NULL /* 사진경로 */
);

COMMENT ON TABLE TEA_PHTOS IS '강사사진';

COMMENT ON COLUMN TEA_PHTOS.TNO IS '강사일련번호';

COMMENT ON COLUMN TEA_PHTOS.PHTO_PATH IS '사진경로';

CREATE UNIQUE INDEX PK_TEA_PHTOS
	ON TEA_PHTOS (
		TNO ASC
	);

ALTER TABLE TEA_PHTOS
	ADD
		CONSTRAINT PK_TEA_PHTOS
		PRIMARY KEY (
			TNO
		);

ALTER TABLE LEC_REQS
	ADD
		CONSTRAINT FK_STUDENTS_TO_LEC_REQS
		FOREIGN KEY (
			SNO
		)
		REFERENCES STUDENTS (
			SNO
		);

ALTER TABLE LEC_REQS
	ADD
		CONSTRAINT FK_LECTS_TO_LEC_REQS
		FOREIGN KEY (
			LNO
		)
		REFERENCES LECTS (
			LNO
		);

ALTER TABLE STUDENTS
	ADD
		CONSTRAINT FK_ADDRS_TO_STUDENTS
		FOREIGN KEY (
			ANO
		)
		REFERENCES ADDRS (
			ANO
		);

ALTER TABLE LECTS
	ADD
		CONSTRAINT FK_MGRS_TO_LECTS
		FOREIGN KEY (
			MNO
		)
		REFERENCES MGRS (
			MNO
		);

ALTER TABLE LECTS
	ADD
		CONSTRAINT FK_CLS_ROOMS_TO_LECTS
		FOREIGN KEY (
			CRNO
		)
		REFERENCES CLS_ROOMS (
			CRNO
		);

ALTER TABLE TEACHS
	ADD
		CONSTRAINT FK_ADDRS_TO_TEACHS
		FOREIGN KEY (
			ANO
		)
		REFERENCES ADDRS (
			ANO
		);

ALTER TABLE LECT_TEACH
	ADD
		CONSTRAINT FK_LECTS_TO_LECT_TEACH
		FOREIGN KEY (
			LNO
		)
		REFERENCES LECTS (
			LNO
		);

ALTER TABLE LECT_TEACH
	ADD
		CONSTRAINT FK_TEACHS_TO_LECT_TEACH
		FOREIGN KEY (
			TNO
		)
		REFERENCES TEACHS (
			TNO
		);

ALTER TABLE CR_PHTOS
	ADD
		CONSTRAINT FK_CLS_ROOMS_TO_CR_PHTOS
		FOREIGN KEY (
			CRNO
		)
		REFERENCES CLS_ROOMS (
			CRNO
		);

ALTER TABLE TEA_PHTOS
	ADD
		CONSTRAINT FK_TEACHS_TO_TEA_PHTOS
		FOREIGN KEY (
			TNO
		)
		REFERENCES TEACHS (
			TNO
		);